; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-coreink]
board = m5stack-coreink
monitor_speed = 115200
upload_speed = 115200
board_build.partitions = custom_4Mb_full.csv
build_src_filter =${env.build_src_filter} +<../boards/m5stack-coreink>
build_flags =
	${env.build_flags}
	-Iboards/m5stack-coreink
	-DCORE_DEBUG_LEVEL=0
	-DUSE_M5GFX=1
	-DHAS_SCREEN=1
	-DHAS_EINK=1
	-DROTATION=3
	-DFP=1
	-DFM=2
	-DFG=3
	-DLITE_VERSION=1 ; limits optional features for 4MB app partition headroom
	-DTFT_WIDTH=200
	-DTFT_HEIGHT=200
	-DDEVICE_NAME='"M5Stack CoreInk"'
	-DHAS_CONTROLLED_POWEROFF=1
	-DHAS_RTC=1
	-DHAS_RTC_BM8563=1
	-DRTC_SDA=21
	-DRTC_SCL=22
	-DBUZZ_PIN=2
	-DBAD_TX=GROVE_SDA
	-DBAD_RX=GROVE_SCL

	; Restrict pin-selection menus to CoreInk-available GPIOs.
	-DGPIO_PIN_LIST='{{"G0", 0}, {"G1", 1}, {"G2", 2}, {"G3", 3}, {"G4", 4}, {"G5", 5}, {"G12", 12}, {"G13", 13}, {"G14", 14}, {"G15", 15}, {"G16", 16}, {"G17", 17}, {"G18", 18}, {"G19", 19}, {"G21", 21}, {"G22", 22}, {"G23", 23}, {"G25", 25}, {"G26", 26}, {"G27", 27}, {"G32", 32}, {"G33", 33}, {"G34", 34}, {"G35", 35}, {"G36", 36}, {"G37", 37}, {"G38", 38}, {"G39", 39}}'

	; Infrared / RF default options on CoreInk
	-DTXLED=GROVE_SDA
	-DRXLED=GROVE_SCL
	-DLED_ON=HIGH
	-DLED_OFF=LOW
	-DIR_TX_PINS='{{"Grove Y", GROVE_SDA}, {"Grove W", GROVE_SCL}, {"G2 (Buzzer)", 2}, {"G5", 5}, {"G12", 12}, {"G13", 13}, {"G14", 14}, {"G15", 15}, {"G18", 18}, {"G19", 19}, {"G23", 23}, {"G25", 25}, {"G26", 26}, {"G27", 27}, {"G32", 32}, {"G33", 33}}'
	-DIR_RX_PINS='{{"Grove W", GROVE_SCL}, {"Grove Y", GROVE_SDA}, {"G34", 34}, {"G35", 35}, {"G36", 36}, {"G37", 37}, {"G38", 38}, {"G39", 39}, {"G5", 5}, {"G12", 12}, {"G13", 13}, {"G14", 14}, {"G15", 15}, {"G18", 18}, {"G19", 19}, {"G23", 23}, {"G25", 25}, {"G26", 26}, {"G27", 27}, {"G32", 32}, {"G33", 33}}'
	-DRF_TX_PINS='{{"Grove Y", GROVE_SDA}, {"Grove W", GROVE_SCL}, {"G2 (Buzzer)", 2}, {"G5", 5}, {"G12", 12}, {"G13", 13}, {"G14", 14}, {"G15", 15}, {"G18", 18}, {"G19", 19}, {"G23", 23}, {"G25", 25}, {"G26", 26}, {"G27", 27}, {"G32", 32}, {"G33", 33}}'
	-DRF_RX_PINS='{{"Grove W", GROVE_SCL}, {"Grove Y", GROVE_SDA}, {"G34", 34}, {"G35", 35}, {"G36", 36}, {"G37", 37}, {"G38", 38}, {"G39", 39}, {"G5", 5}, {"G12", 12}, {"G13", 13}, {"G14", 14}, {"G15", 15}, {"G18", 18}, {"G19", 19}, {"G23", 23}, {"G25", 25}, {"G26", 26}, {"G27", 27}, {"G32", 32}, {"G33", 33}}'

	; Default I2C port
	-DGROVE_SDA=21
	-DGROVE_SCL=22

	; SD Card pins (CoreInk has no onboard SD)
	-DSDCARD_CS=-1
	-DSDCARD_SCK=-1
	-DSDCARD_MISO=-1
	-DSDCARD_MOSI=-1

lib_deps =
	${env.lib_deps}
	m5stack/M5Unified @ ^0.2.11
